version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: school-registry-db
    environment:
      POSTGRES_DB: school_registry
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: school-registry-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school_registry
      SPRING_DATASOURCE_USERNAME: school_user
      SPRING_DATASOURCE_PASSWORD: school_password
    networks:
      - school-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: school-registry-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - school-network

volumes:
  postgres_data:

networks:
  school-network:
    driver: bridge 